// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';
import {timer} from '../models';
import {stats} from '../models';

export function DiscardPausedSession():Promise<boolean>;

export function GetPausedSession():Promise<main.PausedSessionResponse>;

export function GetSettings():Promise<storage.UserSettings>;

export function GetTheme():Promise<string>;

export function GetTimerState():Promise<timer.TimerState>;

export function GetTodayStats():Promise<stats.DailyStatsResponse>;

export function GetWeeklyStats():Promise<Array<stats.DailyStatsResponse>>;

export function PauseTimer():Promise<timer.TimerState>;

export function QuitApp():Promise<void>;

export function ResetTimer():Promise<timer.TimerState>;

export function ResetToDefaults():Promise<storage.UserSettings>;

export function ResumePausedSession():Promise<timer.TimerState>;

export function ResumeTimer():Promise<timer.TimerState>;

export function ShowWindow():Promise<void>;

export function SkipBreakCountdown():Promise<timer.TimerState>;

export function StartFocus():Promise<timer.TimerState>;

export function UpdateSettings(arg1:storage.UserSettings):Promise<storage.UserSettings>;
