// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscardPausedSession() {
  return window['go']['main']['App']['DiscardPausedSession']();
}

export function GetPausedSession() {
  return window['go']['main']['App']['GetPausedSession']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetTimerState() {
  return window['go']['main']['App']['GetTimerState']();
}

export function GetTodayStats() {
  return window['go']['main']['App']['GetTodayStats']();
}

export function GetWeeklyStats() {
  return window['go']['main']['App']['GetWeeklyStats']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function ResetTimer() {
  return window['go']['main']['App']['ResetTimer']();
}

export function ResetToDefaults() {
  return window['go']['main']['App']['ResetToDefaults']();
}

export function ResumePausedSession() {
  return window['go']['main']['App']['ResumePausedSession']();
}

export function ResumeTimer() {
  return window['go']['main']['App']['ResumeTimer']();
}

export function SkipBreakCountdown() {
  return window['go']['main']['App']['SkipBreakCountdown']();
}

export function StartFocus() {
  return window['go']['main']['App']['StartFocus']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
